### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by roksta** [Hilbert70/LEDStream#2]
Hey man, thanks for providing the code. I hope this will reach you since it looks like you're not here very often.

anyways I tried to run your code and I keep getting this message: http://i.imgur.com/AjdpO4Y.png

Hope you can help me out here, I'm really strugglin to get this work...

**Comment by Hilbert70** [comment]
Hi,
It looks like your arduino enviroment is not complete. It seems that you are missing some header files that should be pressent.

**Comment by roksta** [comment]
I'm a total newbie, i received the LPD6803 yesterday and have been frustrated ever since.
My LEDs look color and wirewise like this: http://doityourselfchristmas.com/wiki/images/d/d9/DC_RGB_string.jpg
Using the Arduino UNO and assuming that Red is 5+ and Blue GND, since on the output side those two wires are lose.

I have copied the FastSPI files into the Library and run your LEDstream code. The LEDs are shining white. nothing else happens.

I have been at this for several hours straight. If you could diagnose my sitation somehow, that would be aweseome!
thanks

**Comment by roksta** [comment]
So I'm just going to try and explain my problem, so hopefully someone experienced might diagnose my setup with the following components:
1. Arduino Uno R3 Board
2. 50 LPD6803 LEDs
3. 5V 10amp Power Supply

The Arduino Uno is connected to the PC and the drivers were correctly installed, or so it seems.
It seems I have purchased these: http://store.rebootstudio.com/lpd6803-1 ... led-pixels - According to this source the pin values are: 5V, Clock, Data, Ground, assuming the order of the wires are red(5v), white(clock), green(Data), blue(GND). I was able to read the values on the chip itself: red: 5V, white: CUT, green: DUT, blue: GND (Not sure because its hard to read, very blurry).- After a lot of research I came to the conlusion that the values of the colores must be as described, please tell me if I'm wrong.

On the Arduino Uno I connected the green wire (Data) with pin 11, white(clock) with 13, blue and GND. On the output end of the strip red and blue are connected to the Power Supply. (based on this tutorial: http://learn.adafruit.com/adalight-diy- ... g/overview)

So basically my idea was to upload a LEDstream.pde that has been coded for the LPD6803 and afterwards running them with Lightpack.

 I used this provided code from you https://github.com/Hilbert70/LEDStream/ ... /LEDStream. - Actually I could only guess what I was doing: I copied the FastSpi in to Libraries (not sure where exactly) and uploaded the LEDstream code. The upload seemed succesful. (TX & RX started to flash for a short while)

But the I can't see results of the LEDstream. Whenever the LEDs are connected to the power supply, they only emit the color white. When they're off the Power Supply they are shining red weakly. Without the powersupply the LEDs seem to react to the upload, as in flashing (but only in red). When the PowerSupply is connected, nothing happens but the white color. (might the power supply be to strong?)

After a lot of googling I came to the conlusion that there must be a way to get these working.. there seem to be people who did it succesfully. I really hope not that my components are defective.. So pleeeeas if there is any way, I would really appreciate it. I have been looking forward to this but it has been only frustrating until now. If you need any more information please let me know.

thank you very much!

**Comment by Hilbert70** [comment]
Hi,

The fastSPI library came from http://code.google.com/p/fastspi/ You can download the zip there. In the zip is a stand alone testled program for your LEDs. You should compile and run this program (for the  LPD6803) set it to 50 leds and after the upload the leds should change colour. This is THE test to test the arduino board with your leds. 
The red is +5 V the blue 0V and should be in common with the arduino. Green and white should be on pin 11 and 13.
If the leds do not change colour you should switch 11 and 13.
The LEDS should be on the power supply and the arduino should stay connected to the usb port of your computer.
If the leds are changing colour, you can try my LEDstream and that should work with boblight or any other "ada" compatible program. I tested LEDStream with an adalight test program and that one is also working.
