### ISSUE TITLE
Adding new protocols

### ISSUE THREAD

**Issue by thadrobertson** [Hilbert70/LEDStream#4]
Hello

Not an issue, more of a question.

Am I correct in assuming that if I wanted to add a new protocol I could add a line referencing one supported by FastLED, say:
`e.g. FastSPI_LED.setChipset(CFastSPI_LED::WS2812);
and altering the data rate to suit would work?

**Comment by Hilbert70** [comment]
That is what the comments say ;-) comment out the led chip you don't have and un comment the one you want to have.
It is a rather old version of fast_spi. It should work, but I am not shure, it has been a while

**Comment by thadrobertson** [comment]
Thanks :) I'll give that a try..
